name: train45
contracts_folder: contracts

plugins:
  - name: solidity
  - name: ape-etherscan

solidity:
  version: 0.8.23
  evm_version: paris

ethereum:
  mainnet:
    transaction_acceptance_timeout: 600  # 10 minutes
